New configure town zone multipliers
JGRennison/OpenTTD-patches pull request #228
Opened 2021-03-20 14:49 UTC by reldred

Additional changes to the patch as discussed, now a straight calculation if the feature is enabled or not. Further clarification to menu configuration options. Alas I couldn't figure out how to hide the zone options unless the feature is set to 'True'.

todo when I learn how:
Create various presets
Make the settings menu items for the zone parameters only appear when the drop down is set to 'Custom' rather than 'Default' or one of the pre-sets.
Savegame stuff.

2021-03-20 14:58 UTC, James103 requested changes
I found an obvious typo, where "Use custom town zone calculatio**pn**s" should be "Use custom town zone calculatio**n**s".

2021-03-20 14:58 UTC, James103 commented on src/lang/english.txt
> +STR_CONFIG_SETTING_TOWN_ZONE_CALC_MODE                          :Use custom Town Zone calculatiopns: {STRING2}
```suggestion
STR_CONFIG_SETTING_TOWN_ZONE_CALC_MODE                          :Use custom Town Zone calculations: {STRING2}
```

2021-03-20 14:58 UTC, James103 commented on src/lang/english_AU.txt
> +STR_CONFIG_SETTING_TOWN_ZONE_CALC_MODE                          :Use custom Town Zone calculatiopns: {STRING2}
```suggestion
STR_CONFIG_SETTING_TOWN_ZONE_CALC_MODE                          :Use custom Town Zone calculations: {STRING2}
```

2021-03-20 14:58 UTC, James103 commented on src/lang/english_US.txt
> +STR_CONFIG_SETTING_TOWN_ZONE_CALC_MODE                          :Use custom Town Zone calculatiopns: {STRING2}
```suggestion
STR_CONFIG_SETTING_TOWN_ZONE_CALC_MODE                          :Use custom Town Zone calculations: {STRING2}
```

2021-03-21 01:21 UTC, reldred commented
> 
> 
> I found an obvious typo, where "Use custom town zone calculatio**pn**s" should be "Use custom town zone calculatio**n**s".

Thanks, I've committed those corrections, thanks!

2021-03-25 12:21 UTC, JGRennison commented
Thank for the contribution :).
I've squashed and applied this with some minor adjustments.

2021-03-25 12:21 UTC, closed without merging